import utl

utl.error(utl.CTS, 99, "Arbitrary CTS error message")
